//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.01 at 09:59:58 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datex2.eu/schema/2/2_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.se.datex2.schema;
